In [2]:
import pandas as pd

In [5]:
data= pd.read_csv('./topified_vectorized_Science_1900_2023_cleaned_up.csv')

In [6]:
data.head()

,Unnamed: 0,title_abstract,publicationDate,citationCount,influentialCitationCount,topic_code,topic_list,x_vector,y_vector,z_vector,year,month,year_month
0,0,Acoustical characteristics tinnitus. analysis....,1962-02-01,69,1,20,20_hearing_ear_auditory_hearing loss,2.364143,5.038495,3.597319,1962-01-01,2,1962-02-01
1,1,Reproductive steroids bovine. VI. Changes inte...,1971-07-01,51,0,26,26_hormone_estrogen_lh_pituitary,2.281632,3.871610,6.215812,1971-01-01,7,1971-07-01
2,2,Aluminium saturation I- S-type granites charac...,1999-03-01,1015,139,0,0_species_soil_plant_plants,6.205470,3.753077,8.391185,1999-01-01,3,1999-03-01
3,3,Research development agricultural robotics: pe...,2018-08-08,299,7,0,0_species_soil_plant_plants,4.762645,4.163726,8.538537,2018-01-01,8,2018-08-01
4,4,Modular representations symmetric groups analy...,1951-11-07,51,5,19,19_group_groups_algebras_ring,8.419723,4.441118,4.956598,1951-01-01,11,1951-11-01